name: Build Ubuntu 22.04

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04

    steps:
    - name: Install Dependencies
      run: |
          sudo add-apt-repository ppa:ecal/ecal-latest
          sudo apt-get update
          sudo apt-get install ecal