name: Build Ubuntu 22.04

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04

    steps:
    - name: Install Dependencies
      run: |
          sudo add-apt-repository ppa:ecal/ecal-latest
          sudo apt-get update
          sudo apt-get install ecal qtmultimedia5-dev libqt5multimedia5-plugins qtwayland5 libprotoc-dev protobuf-compiler libhdf5-dev

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules:  'true'
        fetch-depth: 0

    - name: CMake
      run: |
        export CC=/usr/bin/gcc-11
        export CXX=/usr/bin/g++-11
        mkdir "${{ runner.workspace }}/_build"
        cd "${{ runner.workspace }}/_build"
        cmake -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu "${{ runner.workspace }}/ecal-camera-tools"
      shell: bash

    - name: Build Release
      run: cmake --build . --config Release
      working-directory: ${{ runner.workspace }}/_build

    - name: Extract eCAL Version Number
      run: |
        ECAL_VERSION=$(dpkg -s ecal | grep '^Version:' | sed 's@^[^0-9]*\([0-9.]\+\).*@\1@' | cut -d"." -f-2)
        echo "ecal_version=${ECAL_VERSION}" >> "$GITHUB_ENV"

    - name: Read Project Name from CMakeCache
      run: |
        CMAKE_PROJECT_NAME_STRING=$(cat "${{runner.workspace}}/_build/CMakeCache.txt" | grep "^CMAKE_PROJECT_NAME:")
        arr=(${CMAKE_PROJECT_NAME_STRING//=/ })
        CMAKE_PROJECT_NAME=${arr[1]}
        echo "cmake_project_name=$CMAKE_PROJECT_NAME"  >> "$GITHUB_ENV"
      shell: bash

    - name: Pack
      run: cpack -G DEB
      working-directory: ${{ runner.workspace }}/_build

    - name: Rename .deb installer
      run: |
        mv *.deb "${{env.cmake_project_name}}-ubuntu22.04-ecal-${{env.ecal_version}}.deb"
      shell: bash
      working-directory: ${{runner.workspace}}/_build/_deploy/


    - name: Upload Debian
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-debian
        path: ${{ runner.workspace }}/_build/_deploy/*.deb